spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    username: postgres
    password: password123
    driverClassName: org.postgresql.Driver
    hikari:
      max-lifetime: 45000
      keepalive-time: 40000
      idle-timeout: 35000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

server:
  port: 9090
